spornt
EmotionCognitionLab/pvs pull request #200
Opened 2022-05-25 23:08 UTC by Floozutter

4 items per set, 100 seconds per set, and fixes for omitted set 5 and set 11 data.

2022-05-27 18:17 UTC, noah10 requested changes
The changes look ok, but I see that daily-tasks.test.js is failing on the "should save a 'set-finished' result at the end of a set" test. (Specifically at line 522 where it checks to see if saveResults has been called as often as expected.) My guess is that by cutting down the number of trials we cut down the number of times that saveResults gets called, but if you could double-check that and fix the test that would be great.

2022-05-27 23:22 UTC, Floozutter commented
> The changes look ok, but I see that daily-tasks.test.js is failing on the "should save a 'set-finished' result at the end of a set" test. (Specifically at line 522 where it checks to see if saveResults has been called as often as expected.) My guess is that by cutting down the number of trials we cut down the number of times that saveResults gets called, but if you could double-check that and fix the test that would be great.

Changed to:
```
expect(saveResultsMock.mock.calls.length).toBe(
    1  // fullscreen
    + tasksToRun[0].timeline.length  // spatial-orientation trials (no weird control flow)
    + 2  // browser check and set finished
);
```

2022-05-28 18:09 UTC, noah10 reviewed
Looks good!

2022-05-28 18:10 UTC, noah10 approved these changes

2022-05-28 18:10 UTC, merged